### create a movie
POST http://localhost:8080/movies
Content-Type: application/json

{
  "name": "Rambo 3",
  "year": 2023,
  "ageLimit": 12,
  "rating": 4,
  "synopsis": "lorem ipsum",
  "directorId": 1,
  "genreIds": [
    1
  ]
}

### create a movie (validation error)
POST http://localhost:8080/movies
Content-Type: application/json

{
  "name": null,
  "year": 2023,
  "ageLimit": 12,
  "rating": 4,
  "synopsis": "lorem ipsum"
}


### fetch all movies
GET http://localhost:8080/movies

### get specific movie
GET http://localhost:8080/movies/1805

### fetch all genres
GET http://localhost:8080/genres



### create a movie
POST http://localhost:8080/movies/find
Content-Type: text/plain

Rambo
