spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url:
  #     jdbc:h2:mem:movieDb?createDatabaseIfNotExist=true
#      driverClassName:org.h2.Driver
#      username:sa
#      password:password
#  database-platform: org.hibernate.dialect.H2Dialect