logging:
  level:
    root: debug
    de.gentz: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:movieDb?createDatabaseIfNotExist=true
    driverClassName: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true